### ISSUE TITLE
Use metrics-json module

### ISSUE THREAD

**Issue by tonymkhael** [elastic/elasticsearch-metrics-reporter-java#19]
It would be nice for the reporter to use the metrics-json lib (https://github.com/dropwizard/metrics/tree/master/metrics-json).
One of the missing fields in the current JSON serializers is the samples for any metric with a histogram (timer etc..) which could be used in kibana to plot the latest samples instead of plotting statistical values.

**Comment by davidkarlsen** [comment]
That would be nice - but the one in metrics doesn't allow for easy customization (adding fields) - and there is an additionalFields and timestamp in the current imp that would be gone missing: https://github.com/dropwizard/metrics/blob/master/metrics-json/src/main/java/io/dropwizard/metrics/json/MetricsModule.java

**Comment by tonymkhael** [comment]
You're right, sorry for overlooking that. However I'll explain further my initial need.
Suppose I have a timer, and I setup an ElasticsearchReporter to report my timer. What I would like to be able to do in Kibana, is to plot my timer (last sample value) with date histogram bucketing. What's available with the current impl is only the statistical values (stddev, percentials, avg etc..). I saw the samples serialization commented out, and that was why I original created this issue. This for example is very easy to do using simple gauges (because the gauge itself is an instantaneous snapshot of the metric at the time the reporting occurs).

I'll try to find a way to figure it out, and post the solution in case that happens.
Issue closed :)

Thanks

**Comment by davidkarlsen** [comment]
If the one in metrics core could cater for additional fields it would probably invite for wider reuse
