### ISSUE TITLE
No release version compat with es 2.1 avail

### ISSUE THREAD

**Issue by davidkarlsen** [elastic/elasticsearch-metrics-reporter-java#20]
The wiki https://github.com/elastic/elasticsearch-metrics-reporter-java/ says 2.1.1 was released in 2015 - but no 2.1.x is avail on maven central. @spinscale Would you mind pushing out a release?

**Comment by shakuzen** [comment]
:+1:

**Comment by davidkarlsen** [comment]
@spinscale ping?

**Comment by jtullyjtully** [comment]
Is there an anticipated date for the new release?  I would also like to be able to use the library, but am using a later version of ElasticSearch

**Comment by spinscale** [comment]
I could update to the latest 2.2 release and a new release over the next couple of days. Would that be ok?

**Comment by davidkarlsen** [comment]
That sounds great!

**Comment by davidkarlsen** [comment]
Tried fixing the upgrade to 2.2 myself - but ran into this: https://github.com/elastic/elasticsearch/issues/16459

**Comment by spinscale** [comment]
just pushed the release on sonatype.. was lazy and deactivated the security manager for now
