### ISSUE TITLE
Gauge with multiple types

### ISSUE THREAD

**Issue by glureau** [elastic/elasticsearch-metrics-reporter-java#28]
Hello!
I'm using gauge in some places, for recording sometimes String values, sometimes numbers.
Sadly it's saved in the same json field "value" and then Elasticsearch take the first entry to define if it's a text or a number, and then it will fail at some point (in my case it's detected as String so I just cannot use the number values).

What about renaming the "value" field to something like "value_<type>"?

Best Regards,
Greg

**Comment by davidkarlsen** [comment]
Same here - for a boolean field, hitting this: https://github.com/elastic/elasticsearch/issues/10056

**Comment by static-max** [comment]
How about adding a suffix for the value type? Like `value_double`, `value_string` etc.? `value_string` should be set to "not_analyzed" then. This should solve the type problems and add greater flexibility.

**Comment by static-max** [comment]
I created a PR for this: #49

**Comment by glureau** [comment]
@static-max : yes, that was I meant, dunno why it hasn't display the type placeholder, probably the website formatting...

**Comment by glureau** [comment]
Can't edit the original ticket but if it's superseded by #49, feel free to close this one. (Personally, I'm not interested by this feature anymore.)
