### ISSUE TITLE
Configurable time zone

### ISSUE THREAD

**Issue by nilsga** [elastic/elasticsearch-metrics-reporter-java#7]
Unless I have missed something, it is not possible to specify which timezone to use for the timestamp of the metrics data. In our case, the timestamp is off by 2 hours, due to incorrect timezone being used by default. So an option to specify timezone would be very helpful.

**Comment by spinscale** [comment]
hm, the `Clock.getTime()` is calling `System.currentTimeMillis()` which should be UTC... as there is no timezone conversion happening (the timestamp is used), we should take a closer look at your config

**Comment by nilsga** [comment]
It's a while since I looked at this, but I suspect that the real issue was that the server clock was wrong, so you can probably just close it.

**Comment by spinscale** [comment]
thank you so much for coming despite all the time having passed! Closing this, but feel free to reopen if you need to.
